### PR TITLE
Some bugfixes and edits

### PR DESCRIPTION
**Pull request by killer653**
Fixes Nevreans auto talking over sci comms, and allows the nervian language to be used correctly.

### CODE REVIEW

**Comment by killer653** [comment]
Fixed a transformation typo

**Comment by killer653** [comment]
Made spider webs take more nutrition, due to them being vastly overused.

**Comment by Screemonster** [comment]
wait, are they called "nervians" in-game? 'cause it should be "nevreans".

**Comment by antsnap** [comment]
I would revert that spider web change. I think some people were just testing them out for the first time and didn't know how to remove them. I saw one web on arrivals and one in the bar. Maybe I'm missing something though :o

**Comment by killer653** [comment]
"wait, are they called "nervians" in-game? 'cause it should be "nevreans"."
They're called "Nevreans", it's just that it's an odd name to type up, so I made a typo. Fixed.

"I would revert that spider web change. I think some people were just testing them out for the first time and didn't know how to remove them. I saw one web on arrivals and one in the bar. Maybe I'm missing something though :o"

I'll change it back. The round I was on when they were first added there was people constantly eating food just putting them down. There were a bunch of them in the hallways and whatnot. I'm assuming it died down a bit, so I'll revert it.

**Pull request merged**
