### PR TITLE
Added HUD Glasses to officer spawn

### PR DESCRIPTION
**Pull request by HawkerTheGreat**
As above.

### CODE REVIEW

**Comment by Leshana** [comment]
Can we confirm: I thought that you could select this item in custom items, and it gave it selectively only if you were in a security job. Is this true?

**Comment by SpadesNeil** [comment]
Yea, I thought you could pick hud glasses in the custom items slot, too.

**Comment by Arokha** [comment]
You can pick "Security HUD", aka the thing worse than HUDSunglasses.

**Comment by SpadesNeil** [comment]
Well all of the security lockers spawn with hud sunglasses, and correct me if I am mistaken, but you also *don't* spawn with a flasher I think.

**Comment by HawkerTheGreat** [comment]
Yeah, You can pick hudglasses - they come in the lockers as well as flashes which spawn in all of sec's pocket - but security all spawns with glasses except for the normal security guard. Detective, Warden, HoS... All spawn with hud glasses. I only assume it would be better for security officers to have the same.

**Comment by HawkerTheGreat** [comment]
I'm also debating if flash and cuffs should be removed from spawn since they're in security... Technically since they take up inv space, they're clutter for people like me. You end up putting them in your belt anyways, but they spawn in lockers too.

Either way.

**Comment by Leshana** [comment]
Okay that is good enough reason, if all the others do.

**Pull request merged**
