### PR TITLE
Adds K9 and medical unit. Allows said borgs to vore. Fixes a few bugs.

### PR DESCRIPTION
**Pull request by Cameron653**
**Addition**: Medical and security hounds. Allows said borgs to eat crew.

**Notes**: Major kudos to Verkister for coding and spriting. I'm just porting it on over and modifying it to work for our code.

**Sprites**: 
https://gyazo.com/6fdaeef6bd7939f6dd35e1aeaa6a092e 
https://i.gyazo.com/8bad8c445372a6a66200c2ef7511e531.mp4
https://i.gyazo.com/3a5f97913792af3aa774ed5237133a3d.mp4

**Reason for addition**: Because this would be a great thing to add to the server. Allows the medical borg to "vore" and also help people out at the same time. The secborg also has a brig-belly

**PR link**: You're already here!

**Features**:

**Adds two new borg modules.**
**Eating a crew has custom flavor-text.**
**Allows crew to leave the borg-belly via an OOC escape  button if required.**

**K9**

**Stunbaton** (Due to the pounce not working, they'll just have to stunbaton criminals instead. Sorry!)
**Jaws**(10 damage. Can be removed if it's controversial. It does as much as a harmbaton, so it's not that big of a deal. Mainly meant for hostile-mobs. Fluff item, if you will.)
**Cuffs**(Cuff criminal scum.)
**Tongue** (Allows them to lick crew. Can lick up bloody items. Can eat trash and power cells for a small charge. If emagged, it can eat normal items.)
**Boop-module**(Boop people on the nose. Yes. That's all it does.)
**Taser** (All security borgs have one.)
**Police tape-roll** (Block off areas.)
**Security hud** (To see wanted criminals)
**BELLY-BRIG**(Eat criminals. Bring them to the brig. Autoinjects inaprovaline due to the way the sleeper code works, and to prevent suffocation damage. (Also part of how the sleeper code works for borgs.))
(When emagged: Laser gun, a few of the modules are effected.)

**Medical-hound** (They are basically there to eat people and heal them with their stomach. Can heal most damages, but can't exactly fix things like internal damage. (Although, they can eat them so they don't get hurt from broken bones!))

**Small Jaws**(5 damage. Very minor. Their extinguisher does more if not the same.)
**Boop module**(Above)
**Tongue**(Above.)
**Health analyzer**(To see specific damage people have.)
**Med-Belly**(Allows them to "eat" people, aka put them in their stomach and give them healing chemicals/transport them without dragging them across the floor. The module can't function without this.)
**Medical Hud**(See general damage on people)
**Mini-extinguisher**(To put out burning patients.) (Autoinjects inaprovaline. Costs 750 cell charge per 10u injection. Auto-injects inaprovaline (Doesn't require any charge.) Has safeguards to prevent the borg from killing itself.)
**Syringe**(An empty syringe. So they can inject medicines that the chemist made for them.)

(Note: There was an delivery-bag item that allowed borgs to pick up a single item. The code has been left in and commented out in case someone wants to attempt to get it to work, as it was causing errors.)

(If I forgot to mention anything in here, please tell me. I added all the features I can remember, but I might've forgotten one or two.)

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Wow, that was fast. o.o

**Comment by Poojawa** [comment]
Wow. how very inventive.

**Comment by SpadesNeil** [comment]
Yea, it's almost like code is open source or something.

**Comment by SpadesNeil** [comment]
It may be worth adjusting the code at some point to handle sleeper digestion instead of injecting digestion reagents, since that would make the prey keep fizzling even after being spat out.

The original vore code would be a good reference as to how that would be accomplished. We'll have to look into more later.

**Comment by OrbisAnima** [comment]
Cameron, would it be viable to use the pounce that the vox use?

**Comment by killer653** [comment]
Possibly. I Could fiddle around with it and see if I could get it to work

**Comment by OrbisAnima** [comment]
There is also a few aliens types in Colonial marines, wich is a baybased server, wich should work too as a pounce. You will have to be careful of balance with them, I advice keeping some sort of cooldown to avoid spamming of it. There is also an issue with it being used to move into space for the colonial marines one.

**Comment by SpadesNeil** [comment]
Let's not give "pounce" to the K9 borgs. That's getting to be overpowered.

**Comment by killer653** [comment]
They we're originally going to have a pounce that worked once every minute instead of a stunbaton, but seeing as they already have a stun baton there's no reason for the pounce, as it would be weaker than the baton anyways. It'd be a fun feature, but eh, I'be got other things to work on and fix.

**Comment by SpadesNeil** [comment]
I know this is over a year overdue but edited the top post to included "from Citadel" in where we got these sprites.

**Pull request merged**
