### PR TITLE
Adds absorption. Adds tail transfer to stomach. #273

### PR DESCRIPTION
**Pull request by Cameron653**
**Adds absorption into the server**. #273 

**Features**:

Drains 2 nutrition per tick until the prey hits less than 2 nutrition, in which the prey will be "absorbed" https://i.gyazo.com/c380e8ee7d315a2482bd20d0fdf5facb.mp4
(Note: The mob was edited to have so little nutrition they were instantly absorbed. In action, this would take a while unless the player was already starving.)

Absorption moves the prey to an "absorbed" pocket where the predator can release them.
https://i.gyazo.com/72e65d3adc752e04999d7e50dfc20aad.mp4

Allows you to move a prey from your tail to your stomach as an added feature.
https://i.gyazo.com/779393045d7b5f57b9a451025394c5d8.mp4

Allows you to set your "absorbed" area flavor text that prey can see. Saves between rounds.
http://puu.sh/oi9Qw/53bf73441d.png
http://puu.sh/oi9Oy/abbc4c2db9.png

### CODE REVIEW

**Comment by Cameron653** [comment]
Actually saves prefs this time.

**Comment by SpadesNeil** [comment]
Some screenshots would be nice.

**Comment by Cameron653** [comment]
Alright, let me grab some screenshots real quick.

**Comment by Cameron653** [comment]
Screenshots and gifs of the feature in action.

**Comment by antsnap** [comment]
Awesome! I can't wait to do slime char stuff with this~

**Pull request merged**
