### PR TITLE
Fix demon language color URGENT

### PR DESCRIPTION
**Pull request by antsnap**
When I changed the name I forgot to change the stylesheet color name to match :3

### CODE REVIEW

**Comment by antsnap** [comment]
How do I mark this with urgent, because the language.dm won't compile without it probably :3

**Comment by SpadesNeil** [comment]
For future reference, compile before each pull request in future.

**Comment by SpadesNeil** [comment]
Also there's conflicts currently.

**Comment by antsnap** [comment]
ok fixed now

**Pull request merged**
