### PR TITLE
Adds black wolf tail sprite back.

### PR DESCRIPTION
**Pull request by Cameron653**
Adds the black wolf tail sprite back. Fixes issue #390 
Image: http://puu.sh/nf6me/16c8ffd6db.png

### CODE REVIEW

**Comment by SpadesNeil** [comment]
He meant cat ear but this is nice too!

**Comment by Cameron653** [comment]
Added in with #393 to prevent any possible merge errors with the two.

**Comment by SpadesNeil** [comment]
Did this add in the cat tail, also?

**Comment by Cameron653** [comment]
No. I couldn't find the cat tail, only the wolf tail.

**Comment by SpadesNeil** [comment]
It's just the same sprite used for the kitty ears. I think it's just in the wrong file.

**Pull request closed without merging**
