### PR TITLE
Custom Items update #2

### PR DESCRIPTION
**Pull request by OrbisAnima**
*Added Molenar's amazing suits for Sergals and Akulas

*Fixed (Hopefully) Scree's voidsuit

*Added several custom items (that were marked as approved on the forums)
- do note that I commented in the config file the items that were
approved but not coded/couldn't find, like the custom pdas or skinners
clothes, wich should be placed in a box I believe, and given armor as
the forum told.

Hopefully with my code as a guide the rest of the custom items will be
added as needed.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Custom_items.txt is done completely wrong.

**Comment by OrbisAnima** [comment]
It is if we were to use the new bay item spawning, but since we are using the old method, that custom_items.txt is the right one, I even left a comment in there for future pushs

**Comment by OrbisAnima** [comment]
For the Whitelist update, remember to add the players that can go Vox/Diona, and aren't admins, to the alienswhitelist.
the following should work
Drocsid - Vox
Drocsid - All

**Comment by SpadesNeil** [comment]
The whitelist is not functioning correctly yet. If I turn it on, it denies all non-human species.

**Comment by SpadesNeil** [comment]
Drocsid will be whitelisted for Vox.

**Comment by ShadowLarkens** [comment]
@SpadesNeil question, did you intentionally give me collaborator access to this github?

Yes, I realize github comments are probably not the best place for questions, but they are also the quickest way.

**Comment by SpadesNeil** [comment]
Yes. Been meaning to ask you if you wanted in-game "Developer" rank. You've certainly helped enough.

Developer gives access to some vars. No mod powers.

**Comment by OrbisAnima** [comment]
Var edit, Spawn and most importantly, you get to see the logs of stuff when server is dividing by zero

**Comment by SpadesNeil** [comment]
Still a conflict here.

**Comment by ShadowLarkens** [comment]
@SpadesNeil Er, maybe. Quick question though, is there any better way to contact you than the github comments or skype?

**Comment by SpadesNeil** [comment]
Yea, the forum, ya doof.

**Pull request closed without merging**
