### PR TITLE
Port some Vore features

### PR DESCRIPTION
**Pull request by dylanstrategie**
I have mostly followed the files outlined on the Dropbox. The code seldom works and allows basic vore functionality

- Ported all vore sounds
- Ported emote fix (I think Bay's change should have fixed it already, but you can't be too sure I guess)
- Ported custom relaymove, examine, vomit, gib
- Ported basic vore, including all toggles, vars, defines, handling in life code
- Ported grabbing code, note that there was an addition from Bay which I have not handled. Did not cause problems during basic testing
- Removed FILE_DIR. This shouldn't be here, see original Baystation.dme (https://github.com/Baystation12/Baystation12/blob/master/baystation12.dme). From now on, you'll need to uncheck set FILE_DIR for sub-directories in Build > Preferences before compiling, otherwise it'll modify the FILE_DIR
- Due to changes to species by Bay, womb species change is currently commented out since I have not figured how to make it compatible. Furthermore, xenomorphs are now a human sub-species. I don't know either
- Included the hotfixes file. Note that none of the Vore species were ported (especially with that new Bay species system)

I have opted out of doing any modifications and did what is basically a straight port. Basic vore should now work correctly, Vore species and special code changes are most likely still missing

Basic testing was done on this to confirm that grabbing and digestion works. Some things like relaymove couldn't be tested reliably

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I noticed the .dme file got lots of stuff removed.

**Comment by dylanstrategie** [comment]
FILE_DIR defines shouldn't be in the .dme, check Baystation's .dme

**Comment by SpadesNeil** [comment]
Typo that needs fixing on code/modules/mob/living/carbon/human/human.dm line 764. Open HTML span tags. This needs to be fixed.

Need </span> tags.

**Comment by dylanstrategie** [comment]
Typo fixed for further notice

**Pull request merged**
