### PR TITLE
Re-add Predator Law Module, AI law tweaks.

### PR DESCRIPTION
**Pull request by Arokha**
Added it ingame using revamped laws (addresses #109)
Added it to mining loot (replaced syndie ballon because BLAH)

Also corrected AI laws to refer to crew, not humans, since Virgo is way more diverse than normal bay and species aren't all whitelist.

### CODE REVIEW

**Comment by nightwingthedragon** [comment]
Syndicate balloon is awesome! I gotta ask, why replace the balloon instead of simply adding the module?

**Comment by Arokha** [comment]
All the numbers up to way high are already taken. D: The way it appears to have been done is just... RNG roll number, if 1-5 then these items, 6-10 these items, 11 or 12 these items, 13 these items, etc. It's all nice and in order of probabilities and I'd have to redo ALL the numbers ALL the way up if I wanted to add something with a probability of greater than 1-in-MAX which I think the pred board should come more often than that extremely off chance. Also if I did that, I'd change the probability of EVERY item and I'm not comfortable messing with that.

**Comment by nightwingthedragon** [comment]
So, for the balloon and the board, instead of 
```
if(57 to 58)
-			new/obj/item/toy/syndicateballoon(src)
+			new/obj/item/weapon/aiModule/predator(src)
```

Try

```
if(57)
			new/obj/item/toy/syndicateballoon(src)
if(58)
			new/obj/item/weapon/aiModule/predator(src)
```

**Comment by Arokha** [comment]
But I want it to have a higher chance of spawning, so I wanted it to have at least two numbers. I could add it WITH the syndie balloon? :P Are you just being argumentative or do you actually really want the syndie balloon? XD

**Comment by nightwingthedragon** [comment]
What I'm sayin' is, this thing's already obtainable in the game, but it's never used because even when we do find it, there's often not an AI online at the time and if there is, most people wouldn't want the predator board loaded onto the AI. Whereas the syndicate balloon can be used by most people because it's a fun item that you just carry around. Don't replace, just add :P

**Comment by Arokha** [comment]
Like I said, I'd have to renumber all the other items to keep it the same stylistically. The higher probability ones come earlier. If I wanted to shove one in higher, I'd need to renumber everything after it, and increase the max RNG value. Doing this also REDUCES the chances of every other item, which I didn't want to do.

If you really care about the syndie balloon, pick another item that gets at least two numbers.

Or, we can just put it in the AI core with the other bad boards.

**Comment by nightwingthedragon** [comment]
But, why does the chance of getting this board and the balloon HAVE to be consistent with the 58 or 59 chance? Why not be half the chance for each? That's what I don't get.

**Comment by Arokha** [comment]
Maybe I'm communicating poorly. Here are the facts:
> The RNG is set to pick a number from 1 to 100 right now.
> Having one number the die could land on is a 1:100 chance.
> Having two numbers the die could land on is a 1:50 chance.
> The order of the items in the source code is from most common to most rare.

Here are my thoughts:
> Pred board should happen more often than 1:100 chance.
> Two numbers gives it a 1:50 and that's good enough.
> I don't want to adjust the RNG to do 1 - 102 or anything.
> Even if I did, I'd have to add the pred board as 87-88 because that is where the chances switch from 1:50 to 1:100.
> If I did that, I'd have to renumber all the rest of the items.
> Doing this also makes every item more rare. The pred board then has a 1:51 chance, all the other items have a 1:102 chance, and the earlier ones that have 4 or 5 numbers don't divide evenly at all anymore, having like 1:20.4 chance.

It's just a lot cleaner this way.

**Pull request closed without merging**
