### PR TITLE
Completely fixes womb TF. (No taur fix button needed.)

### PR DESCRIPTION
**Pull request by Cameron653**
Completely fixes womb transformations.  
Automatically updates the taur half, so the hotfix button isn't needed anymore.

Also makes it so the "change species" actually changes the prey's species and taur.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Bit of a hacky hotfix. What we really need to do is fix the taur sprites on update_icons while resized.

**Comment by Cameron653** [comment]
I mainly did the first thing that came to mind. Let me see if I can get "P.update_icons()" to work for the tf.

**Comment by Cameron653** [comment]
Testing a possible fix

**Comment by Cameron653** [comment]
Made a fix that makes hair color, species, and eye color automatically occur. Really can't make the taur automatically appear without the taur fix button, as it's out of my knowledge. What is here currently is about as good as I can get it.

**Comment by Cameron653** [comment]
Made a fix, taur halves now automatically show up, now hotfix button needed.

**Comment by Cameron653** [comment]
Title changed to clarify that it's completely automatic, and doesn't require the prey to update their icon by using the fix taur button anymore.

**Pull request merged**
