### PR TITLE
Adds Nervean race, language, and monkey.

### PR DESCRIPTION
**Pull request by Cameron653**
Adds Nervean race, language, and the monkey to the code.

Race: http://puu.sh/niRzX/8dc53d1138.png
Language: Birdsong. Consists of cheeps, peeps, and tweets. Spoken using :n 
Monkey: Not much to say here. Called a sparra. http://puu.sh/niUjX/2b380f138b.png
Tail: Adds a new Nervean tail, able to be used by any race, and the Nervean spawns with it.
Hardsuit: Has same sprites as Unathi, hardsuit wise.

Adds: #398 #399 #400

### CODE REVIEW

**Comment by Cameron653** [comment]
Do not merge. Need to fix monkey sprites

**Comment by Cameron653** [comment]
Now it's ready for merge.

**Comment by SpadesNeil** [comment]
I kind of want to wait until we have suit sprites too.

**Comment by Cameron653** [comment]
I could close the PR until then if you'd like. Also, DNM right now, need to fix the monkey sprite.

**Comment by antsnap** [comment]
Oooh they look awesome. Good work :3

**Comment by Cameron653** [comment]
Alright, /now/ it's fixed. The Sparra monkey now functions as needed.

**Comment by Cameron653** [comment]
Also, the hardsuit sprites aren't a major issue. They could be added in, but it isn't an huge problem, and the time it'd take to wait for someone to make hardsuit sprites for them may take longer than it did to create the character sprites and the code itself.

**Comment by Screemonster** [comment]
suit sprites will take bloody ages for all the suits. for now their body-shape is such that it'll fit in unathi-suits though the birds might ICly complain about it.

**Comment by SpadesNeil** [comment]
Let's at least make a placeholder file. Copypaste the Unathi .dmi files and rename them, and change the code to match the new files. This way we only have to replace the sprites later.

**Comment by Cameron653** [comment]
Alright. Going to make that in a minute.

**Comment by Cameron653** [comment]
Placeholders added. It should work. Going to test it in a moment.

**Comment by Cameron653** [comment]
I tested almost everything I could think of, added a placeholder area with Unathi hardsuit sprites, along with a few fixes. Suit cyclers now dispense the voidsuits for Nevrean birds.

**Pull request merged**
