### PR TITLE
Custom Items Easter Update!

### PR DESCRIPTION
**Pull request by JoanRisu**
Ironically, the only item with remote relations to Easter is the white bunny ears. 

Items being added include:
Big Iron + Flash Ammo
Purple Medhud
Lethe's Hat
White Bunny Ears

Minor change:
~Edited HoS hat (and collectable) filepath to follow standard lowercase naming.

### CODE REVIEW

**Comment by antsnap** [comment]
Ho ho ho

**Comment by SpadesNeil** [comment]
I thought Big Iron was supposed to have wax bullets.

They also need to be added to the autolathe.

**Comment by JoanRisu** [comment]
Do we have wax bullets? I also don't know where to add autolathe stuff.

**Comment by SpadesNeil** [comment]
Remove the flash bullets and comment out the Big Iron. I'll do it since idk how to change -your- PR.

**Comment by SpadesNeil** [comment]
Actually I'll work on it.

**Comment by SpadesNeil** [comment]
Okay so I'm immediately seeing problems with Big Iron not behaving realistically so I'm going to replace it with a .38 version instead.

**Comment by JoanRisu** [comment]
That's fine. A lot of this is initial stuff to get them into the system since we've been putting this off for so long.

**Pull request merged**
