### PR TITLE
Final touches

### PR DESCRIPTION
**Pull request by SpadesNeil**
Demi ears added.
Replaced all instances of Nyx with Virgo Prime.
Replaced all instances of CentComm with CentCom for consistency.
Replaced all instances of Exodus with V.O.R.E. excluding a spot in one_click_antag.dm, for the Vox.
Replaced Icarus with Daedalus.
Replaced NSV and NMV with NDV because consistency is apparently something Bay doesn't know how to do.
Moved medals to medals.dm to be easier to find.
Removed duplicate captain space suit because dumb cay coders.
Solid phoron stuff is called phorite by request of Scree. The material is still known as phoron, obviously.
Config.txt adjustments
Thalers are now credits.
Airlocks now have windows.
(Map) Science got insulated gloves to hack the autolathe.
Removed ripley/ody crates from cargo.
Overhauled the shit out of cargo's supplies.
Added giftbox.dm which contains my contraband box code (for cargo).
Tactical headset added.
Changed title screen.
Added some sound files for music.
Changed AI sound files.

ToDo:
Code the intro music to use our music.
Make use of all of the AI sounds where it's still missing.
Adjust news stories more.
I commented out a bunch of things from the cargo code, such as UNSC gear, or Colonial Marines gear, and various other things that we do not have icons for, but aren't vitally important. We can re-add these goodies at our leisure.
Fluff items from the old code have not been properly imported. Those who have filled applications should have their fluff items added.
Apparently there's a late-join option for the bluespace gateway. I have not removed this yet. It needs to be removed, since we actually use the gateway for other things.

### CODE REVIEW

**Comment by OrbisAnima** [comment]
I will upload the stuff I did for me, Scree and Tassald in a bit, if you wish

**Comment by Michab02** [comment]
Bear in mind that the hyperspace gateway latejoin code might cause issues if someone selects it, because I removed the landmarks it points to when I overhauled the gateway.

**Comment by SpadesNeil** [comment]
I want to outright disable the hyperspace gateway latejoin code completely. Is that the phrasing it uses? Hyperspace gateway? Becuase if so I can dive into the code later, Ctrl+F that phrase, and literally just comment out all references to it.

**Comment by Michab02** [comment]
IIRC, the specific wording it uses is "X has completed translation from an off-site gateway".

**Comment by SpadesNeil** [comment]
Well Imma leave this up for a bit, then merge it if no one sees any problems with it. Then I'll go fix that. We have until the 25th for last updates before the code goes live.

**Pull request merged**
