### PR TITLE
Adds a new feathered wing sprite

### PR DESCRIPTION
**Pull request by Cameron653**
Adds a feathered wing sprite.

Credit to Verkister for the sprites.
For reference as to what they look like:

http://puu.sh/n2aPh/ce9b515467.png
http://puu.sh/n2aPL/2fa3135deb.png
http://puu.sh/n2aQe/4a5cb78217.png
http://puu.sh/n2aQv/a48fa8b98b.png

### CODE REVIEW

**Comment by antsnap** [comment]
Pretty :3

**Comment by killer653** [comment]
Also, Github decided to randomly put my skeleton hotfix in here, so it'll fix the skeleton and add wings.

**Comment by Cameron653** [comment]
There, fixed the skeleton hotfix to not be in here. Sometimes, I hate GitHub.

**Comment by SpadesNeil** [comment]
Very nice sprites.

**Pull request merged**
