### PR TITLE
Horns and tiger bikini (Updated to fix conflict. Mergable now!)

### PR DESCRIPTION
**Pull request by antsnap**
Added cute stubby Oni horns, as well as demon horns. They are selectable under ear styles during player setup.

Also added a cute tiger bikini. It's available in the Univend, and is also available in the custom loadout menu during player setup.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I seem to have created conflicts by merging something else.

**Comment by antsnap** [comment]
Oh no~

**Comment by antsnap** [comment]
My guess is that it's the sprite .dmi files. Just open mine, and the current ones, and manually copy and paste the sprites from mine as new entries in yours.

**Comment by Screemonster** [comment]
Probably the tiger bikini conflicting with all the things that were added to the uniforms file when the mankini and nudity permit were added.

**Comment by SpadesNeil** [comment]
It's your PR. You do it. :U

**Comment by antsnap** [comment]
Oki ima do it. Ill delete this PR and make a new one

**Comment by antsnap** [comment]
wait i don't think I need to resubmit.

**Pull request merged**
