### PR TITLE
Gateway sound

### LINKED ISSUE #600: Give the gateway a sound effect on use
Makes the mechanic more juicy.

### PR DESCRIPTION
**Pull request by Arokha**
VWIIIZSHHHH.

Resolves #600

### CODE REVIEW

**Comment by SpadesNeil** [comment]
centeraway/process() needs this too!

**Comment by Arokha** [comment]
Um but process() is called each time the process controller iterates over it. That’d play every controller tick. c.c; You sure about dis? Unless process() here means something entirely different. Lemme look.

**Comment by Arokha** [comment]
Yeah if I add it to process() it’ll play every tick. Dis seems like bad ideas.

**Comment by SpadesNeil** [comment]
Sorry I'm an idiot. I mean

 /obj/machinery/gateway/centeraway/Bumped(atom/movable/M as mob|obj)

You only did:
 /obj/machinery/gateway/centerstation/Bumped(atom/movable/M as mob|obj)

**Comment by Arokha** [comment]
Fwoop. Did.

**Pull request merged**
