### PR TITLE
Adds postvore UB/CV remains

### PR DESCRIPTION
**Pull request by Cameron653**
Adds semen and femjuice when a crew member is digested using a womb/cock.

Features:
Femjuice and semen sprites (Recolored green-glow sprite)
Both disappear after 2 minutes.
Only lets you squirt out femjuice/semen if you digested someone using that organ, to prevent it from being spammed.

Addresses issue #412 

Feel free to discuss it here/the  forum post below to see if it should be added in.
http://forum.vore-station.net/viewtopic.php?f=23&t=523&p=3245#p3245

### CODE REVIEW

**Comment by Arokha** [comment]
Like I mentioned in the issue for this, you should probably ask the forum about this. Last I asked, there was overwhelming support for not adding any 'remains' of any kind. Maybe sentiment has changed, but... you should add a forum thread and discuss first. #412

**Comment by Cameron653** [comment]
Ah, my bad. I didn't look at the issue earlier. I'll post a forum post about it and see if people want it.

**Comment by SpadesNeil** [comment]
In future, hold off on doing a PR with a "discuss" tag on it until it's been, well, discussed. At least for a week or two.

**Comment by SpadesNeil** [comment]
Title change because reasons I care not to explain. :P

**Comment by Cameron653** [comment]
Ah, yeah. My bad on the title, haha.

**Comment by Cameron653** [comment]
AH, github forgot to sync something. Fixed now.

**Comment by Cameron653** [comment]
Closing this, since it's obvious people do not want it.

**Pull request closed without merging**
