### PR TITLE
Ears/Tails Character Setup

### PR DESCRIPTION
**Pull request by Arokha**
No more silly demi items. Pick them in character setup, have them not get
in the way of your helmets, and keep them through cloning.

Also added ears and tail UI to genetics so you can mutate through all the
possible choices. Good times.

Please don't add tail+ear combo sprites anymore.

Add tails to sprite_accessories.dm at the bottom.

### CODE REVIEW

**Comment by Arokha** [comment]
Don't merge this yet, needs one more commit to change some stuff.

**Comment by Arokha** [comment]
And now stuff has been changed. Huzzah.

**Comment by Arokha** [comment]
Even more goodness.

**Comment by SpadesNeil** [comment]
If this breaks, you're taurpudge, Arokha. :U

**Pull request merged**
