### PR TITLE
Back sprite fix, clockwork rifle, nose

### LINKED ISSUE #314: Exosuit slot uses belt_mirror.dmi instead of back.dmi
Appears to be a mistake, since this means we are missing out on a bunch of the sprites in the totally unused back.dmi file.

### PR DESCRIPTION
**Pull request by Arokha**
Fixes an issue where the back sprite uses belt_mirror.dmi instead of back.dmi.
Changes Aronai's face's nose to be black! Ha!
Added an approved custom item (clockwork rifle) and associated approved permit (for Kari Akiren)

Fixes #314

### CODE REVIEW

**Comment by OrbisAnima** [comment]
If this gets merged in, it will have problems with https://github.com/SpadesNeil/VOREstation/pull/311, @JoanRisu  and @Arokha should resolve the issues in this.

**Comment by JoanRisu** [comment]
@Arokha and I discussed it and we decided to merge mine first before merging this one. We just need to resolve the dmi issue which shouldn't take long and I'll merge this in.

**Comment by SpadesNeil** [comment]
So is the DMI issue fixed?

**Comment by JoanRisu** [comment]
Still trying to figure it out.

**Comment by Leshana** [comment]
Wooosh!

**Pull request merged**
