### PR TITLE
Dev night - Taurs

### PR DESCRIPTION
**Pull request by nightwingthedragon**
Modified the relevant files for taur bodies to be used in the game again. See individual files for specific changes.

### CODE REVIEW

**Comment by ShadowLarkens** [comment]
Seems like it is merge conflicting in human defines, possibly because of the included resize commits.

**Comment by nightwingthedragon** [comment]
Yeah, the first two commits actually shouldn't be there, but since this is pretty much my first time using, I forgot to rebase first. How can I remove the commits "Resize" and "Quickfix - playersize"?

**Comment by ShadowLarkens** [comment]
@nightwingthedragon Couldn't say without knowing which program you use- github for windows, git-scm's command-line, smartgit, etc.

**Comment by nightwingthedragon** [comment]
Github for windows would be the one I use there, but I can use the powershell command line if need be.

**Comment by ShadowLarkens** [comment]
@nightwingthedragon Not paticularly familiar with github for windows.

I would run a command line and use the following;
`git reset --hard origin/master` (resets entire folder to exact state of the remote origin's master branch)
`git cherry-pick 1cdc3b8` (cherry-picks the taur commit, which means it just copies it independant of the other commits)
fix any merge conflicts
`git add & git commit` to add the resolved conflicts
`git cherry-pick --continue` (allows the cherry pick process to finish)
then 
`git push -f origin DEV-night` (force-pushes to the branch "DEV-night", ignoring that it's not a strict update)

**Comment by ShadowLarkens** [comment]
@nightwingthedragon That's if you want to fix the merge conflict of course- I was going to offer to make another PR for this system with a cleanup included, provided you do not mind, of course.

**Comment by nightwingthedragon** [comment]
Annoyingly, I was hoping to get all this done today, due to me leaving on a vacation tomorrow so I won't have internet access for some four weeks. If you could port my taurs patch across, I'd really appreciate it >w>

**Comment by ShadowLarkens** [comment]
@nightwingthedragon In case you didn't get a notification, I put up #5 for the purpose.

**Pull request closed without merging**
