### PR TITLE
Fix for #494

### LINKED ISSUE #494: Exosuits don't register ID's placed in wallet
As the title says - when you have an ID in your wallet, it provides access for you, just as placing it in a PDA... but exosuits don't register them.

### PR DESCRIPTION
**Pull request by Arokha**
Lets you use wallets on exosuits (and rigsuits because I was not 100% sure
what the person reporting it was referring to, and both needed fixing).

Fixes #494

### CODE REVIEW

**Comment by Arokha** [comment]
Ignore, this wasn't what he meant, but still should have been fixed. Will include in full fix.

**Comment by Arokha** [comment]
Nevermind I was right and already fixed in the first PR.

**Comment by SpadesNeil** [comment]
So this fixes preventing players from getting into exosuits while their ID is in a wallet?

**Comment by Arokha** [comment]
Yes, and allows you to whap exosuits to get the maintenance menu with them in a wallet, and also open the maintenance panel on rigsuits with ID in a wallet. You can pretend it's the wallet upgrade.

**Comment by SpadesNeil** [comment]
I don't think that is what they were asking to be fixed.

**Comment by Arokha** [comment]
What do you think it was?

**Comment by SpadesNeil** [comment]
>Don't actually remember if I tested that. I meant for providing access to enter the exosuit.

**Comment by SpadesNeil** [comment]
Oh, nevermind.
> Having a secured mech (security mechs etc) and getting in while your ID is in a wallet

**Pull request merged**
