### PR TITLE
Custom item boxes

### PR DESCRIPTION
**Pull request by JoanRisu**
Edited the squirrel box and added Serkii's custom item box.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I need to add the item to his inventory. I'll merge this when I do that.

**Comment by JoanRisu** [comment]
Remember, Chu just need to add the box. Not the permit.

Add me box to my inventory while chu at it.

**Comment by Arokha** [comment]
Put the path of your boxes here and I'll do it. And remind me Serkii's last name. Miishi? Mishi? Hell just put both your ckeys and full character names, and the paths of the boxes.

**Comment by SpadesNeil** [comment]
eekasqueak:Serkii Miishy:/obj/item/weapon/storage/box/fluff/serkii

**Comment by JoanRisu** [comment]
joanrisu:Joan Risu:/obj/item/weapon/storage/box/fluff/joanrisu

**Comment by JoanRisu** [comment]
Is this being merged any time soon? I wanna close my fork.

**Comment by SpadesNeil** [comment]
/obj/item/clothing/suit/storage/fluff/fedcapt causes a compile error.

**Comment by JoanRisu** [comment]
Huh? It should be in there. What's the line?

**Comment by JoanRisu** [comment]
Or did I put the wrong syntax?

**Comment by JoanRisu** [comment]
Ok, I know what happened. I put fluff/fedcapt instead of fluff/fedcoat/fedcapt

/obj/item/clothing/suit/storage/fluff/fedcoat/fedcapt

**Pull request merged**
