### PR TITLE
Clean up a few things.

### PR DESCRIPTION
**Pull request by ShadowLarkens**
Things changed:
 - Renamed all the `endo` verbs to `digest_(stomach/cock/boob/whatever)`
  - Should be hopefully less confusing.
 - Cleans up the cat and parrot files a bit.
  - did anyone notice that parrots cannot actually pick anyone up
 - Adds a few more constants, used for averaging. These don't ever need to be changed, they just find the average between all of the sizes, for better admin compatibility.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Why is digestion on by default?

**Comment by nightwingthedragon** [comment]
I really gotta ask, Shadow, but why the averages for size?

And when you say "parrots cannot actually pick anyone up", I assume you mean "off the floor"? That's correct. They snatch micros out of hands, not off the floor.

**Comment by ShadowLarkens** [comment]
@nightwingthedragon Well, you mentioned that having the strict constants is limiting to adminbuse; figured, if you calculate the average between each size, admins can have values anywhere around a size and have the correct functions active.
Also, about the parrots, _everything makes sense now._

@SpadesNeil Left over from the original port, I assume.

**Comment by SpadesNeil** [comment]
I do not want digestion on by default. That is not intended. It should be off by default.

**Comment by nightwingthedragon** [comment]
I'm personally still of the opinion that regular float values for playerscale is better than adding nine different hard-coded constants and then going back to look up the value of each one whenever you're unsure...

**Comment by ShadowLarkens** [comment]
@nightwingthedragon I'd say the same applies either way; Either you have to remember the value of each constant when you make something, or you have to remember the constant and look up it's value.

**Comment by SpadesNeil** [comment]
I need to push some hotfixes so work this out, would you guys?

**Comment by SpadesNeil** [comment]
Actually y'know what I'm of the opinion that I do not want constant variables. We sometimes deliberately adjust them in-game to non-standard sizes for events or other reasons.

**Comment by ShadowLarkens** [comment]
@SpadesNeil Okay, I have to point this out, because I think there are misunderstandings of what these actually are for.

The constant variables do not mean you can't change the playerscale in game; You can still do that.
They are essentially just a named version of the floats. Instead of `if(playerscale == 0.25)`, it's more readable to put `if(playerscale == PLAYER_SIZE_TINY)`.

The averages are my solution to non-standard sizes; It makes a range of where the playerscale can be.
Would it be easier to define this as just 0.3? Sure, it probably would be. But, let's have an example.

Cats only target near-tiny people, right? It was if(playerscale <= 0.3). This means that if an admin sets a playerscale anywhere that is less than or equal to 0.3, the code will run.
Using the averages, currently, we have small = 0.5, tiny = 0.25. So, the average of that is 0.375.
This means the range for that code to activate is from right between small and tiny, and downwards.

**Comment by SpadesNeil** [comment]
Oh. Alright. That makes more sense.

**Pull request merged**
