### PR TITLE
Fixes species whitelist to be consistent

### PR DESCRIPTION
**Pull request by Arokha**
Now it ONLY uses the "IS_WHITELISTED" species flag, not a magic text list.

### CODE REVIEW

**Comment by Arokha** [comment]
Trial by fire'd by being on the live server.

**Comment by Arokha** [comment]
why did I click that

**Comment by ForFoxSake** [comment]
Just click all the buttons, one of them will work.

**Comment by Arokha** [comment]
I am tired!

**Comment by SpadesNeil** [comment]
https://github.com/SpadesNeil/VOREstation/issues/627 Whitelist problems are back.

**Pull request merged**
