### PR TITLE
Allows species specific tails to be chosen.

### PR DESCRIPTION
**Pull request by killer653**
Allows any race to have another races tail (Ex: Tajaran with Sergal tail.) ALSO incorperates #392 
Adresses issue #385

### CODE REVIEW

**Comment by Cameron653** [comment]
Sprites:
http://puu.sh/nf8X6/2339ed2b4c.png

**Comment by SpadesNeil** [comment]
So is the black-only cat tail also included here? Because #392 only had the wolf tail. This was a request from Kisuke.

**Comment by Cameron653** [comment]
This one has the black wolf tail, but not the black-only cat tail. I couldn't find the black cat tail anywhere in the icons. I might've not been looking hard enough, but I didn't see it anywhere in there.

**Comment by SpadesNeil** [comment]
It might have to be chopped out of the cat ears sprite. I'll worry about this later.

**Pull request merged**
