### PR TITLE
Make Micro/Macro Reagents Craftable

### PR DESCRIPTION
**Pull request by Leshana**
* Added "Normalcillin" a drug that returns you to normal size!
* Refactored the code for these reagents, removed dead code and cleaned
up the if statements to make it more datum driven and remove
duplication.
* Added chemistry recipes for crafting the micro/macro/normal cillin
* Added "sizeoxadone" as an intermediate precursor to them for game
balance.
* Added a fun effect upon mixing micro and macrocillin together.

### CODE REVIEW

**Comment by Leshana** [comment]
I've tested all this, but I'd like some input on the actual recipes for creating micro/macrocilian etc. I am pretty sure that the sizeoxadone precursor is a good plan (the idea was to make it non-trivial to make, since even just 1 unit is enough to shrink someone)
But I basically picked precursor chemicals that seemed interesting, there might be ones that would have better lore or balance.

**Comment by OrbisAnima** [comment]
I would use something else instead of Doctor Delight, I believe that Phoron as a catalyst is good, but a barmans Drink is not so much... clonexodane might be nice, since it with bicardine and phoron is the precursor to the wonder drug that regenerates organs. I would go with clonex, phoron as catalyst and something else...ethanol maybe? or tramadol as you set.

**Comment by SpadesNeil** [comment]
Remove this "do not merge" tag once you guys work out the recipe.

**Comment by Leshana** [comment]
That seems reasonable enough. I have changed it to be clonexadone.   Everything else look good?

**Comment by OrbisAnima** [comment]
I think it's perfect!

**Pull request merged**
